version: '3.9'

services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "5001:5000"

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "5002:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
